# Generated by Django 5.2.6 on 2025-09-26 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_disciplina', models.CharField(max_length=10)),
                ('nome_curso', models.CharField(max_length=120)),
                ('carga_horaria', models.IntegerField()),
                ('ativo_disciplina', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='curso.curso')),
            ],
        ),
    ]
