# Generated by Django 5.2.6 on 2025-09-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='nome_curso',
            new_name='nome_disciplina',
        ),
    ]
