# Generated by Django 5.2.6 on 2025-09-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
    ]
