# Generated by Django 5.2.6 on 2025-09-26 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_curso', models.CharField(max_length=10, unique=True)),
                ('nome_curso', models.CharField(max_length=120)),
                ('descricao_curso', models.TextField(blank=True, null=True)),
                ('ativo_curso', models.BooleanField(default=True)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
    ]
